Created new way of queueing and prompting
DELTA-GLOW-2023/glow-2023-backend pull request #12
Opened 2023-10-27 12:55 UTC by BartvanEijkelenburg

2023-10-28 12:32 UTC, Vitality-Booster requested changes
Looks good. just a couple of clarification questions and a tip from side :)

2023-10-28 12:32 UTC, Vitality-Booster commented on src/router/promptRouter.ts
> +    }
Can we put the Authorization as a middleware for the whole "promptRouter"? Nothing special, will just get rid of some repetition, which is always satisfying :)

2023-10-28 12:32 UTC, Vitality-Booster commented on src/router/promptRouter.ts
> +  }).sort({ createdAt: 1 });
This sorts oldest first, right?

2023-10-28 12:32 UTC, Vitality-Booster commented on src/service/generateImageService.ts
> +  const latestValidPrompt = await PromptModel.findOne({
Is this function supposed to work infinitely and only stop for 2 seconds when there are no inputs left?

2023-10-28 12:32 UTC, Vitality-Booster commented on src/router/viewImageRouter.ts
> +  }
What is the point of this function and why only authorized users can access it?

2023-10-30 08:35 UTC, BartvanEijkelenburg commented on src/model/promptModel.ts
>  }
Currently there is a different implementation of the panic "button" however, this needs to be discussed with Tim.

2023-10-30 08:35 UTC, BartvanEijkelenburg commented on src/router/imageProcessRouter.ts
> +            // await filterPrompt(prompt);
Yeah!

2023-10-30 08:36 UTC, BartvanEijkelenburg commented on src/model/promptImageModel.ts
> +  imagePrompt: string;
Not really sure, since it is nice to have it separated I would say, and it would require a small refactor (again) to link those models.

2023-10-30 08:36 UTC, BartvanEijkelenburg commented on src/router/promptRouter.ts
> +  }).sort({ createdAt: 1 });
Yeah so the top displayed in the frontend is also the oldest

2023-10-30 08:36 UTC, BartvanEijkelenburg commented on src/service/generateImageService.ts
> +  const latestValidPrompt = await PromptModel.findOne({
Yeah, like that indeed

2023-10-30 08:37 UTC, BartvanEijkelenburg commented on src/router/viewImageRouter.ts
> +  }
Yeah this is an endpoint to show all images stored in the DB so I just put some random auth in it

2023-10-30 08:42 UTC, BartvanEijkelenburg commented on src/router/promptRouter.ts
> +    }
Check! :)

2023-10-30 09:31 UTC, Vitality-Booster commented on src/router/viewImageRouter.ts
> +  }
But should it have the auth or not? I mean, there is no auth to receive a single image, so is there a point in this auth if it's also, as far as I understand, gonna be accessed by the display "front-end" rather than the "admin". Or maybe, to have everything completely secure, we may also have a separate auth for non-admin part

2023-10-30 09:49 UTC, Vitality-Booster commented on src/router/viewImageRouter.ts
> +  }
Ok, makes sense then

2023-10-30 09:51 UTC, Vitality-Booster approved these changes
All good. You can merge :)

2023-10-30 09:57 UTC, merged