Feat/panic
DELTA-GLOW-2023/glow-2023-backend pull request #13
Opened 2023-10-30 11:59 UTC by xl3ehindTim

Change the panic feature to the new queue structure

2023-10-30 12:02 UTC, BartvanEijkelenburg commented on src/router/deleteImageRouter.ts
> +	await addApprovedPromptModel('vulcano');
```suggestion
	await addApprovedPromptModel('vulcano');
```

2023-10-30 12:02 UTC, BartvanEijkelenburg requested changes
Paar dingetjes besproken f2f

2023-10-30 12:31 UTC, xl3ehindTim commented
More panic prompts should be added

2023-10-30 12:37 UTC, BartvanEijkelenburg commented on src/model/promptModel.ts
> +    hasPriority: { type: Boolean, default: false, required: false },
```suggestion
    isPanic: { type: Boolean, default: false, required: false },
```

2023-10-30 12:37 UTC, BartvanEijkelenburg commented on src/model/promptModel.ts
> +  hasPriority: boolean;
```suggestion
  isPanic: boolean;
```

2023-10-30 12:38 UTC, BartvanEijkelenburg reviewed
I think this is a nice solution :) 
Well done!

2023-11-03 11:13 UTC, BartvanEijkelenburg approved these changes
LGTM

2023-11-06 10:42 UTC, merged